### ISSUE TITLE
Propunere workaround alocare spatiu

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#3]
Incercand sa contribui cu ceva cocncret :) 

Pe scurt : 
 - Creat o metoda care calculeaza spatiul necesar pentru torentele ce nu s-au descarcat complet 
     - Nume: getDownloadingTorrentsSpaceNeeded
     - Clasa:  Connection
 - Modificat torrent info pentru a include si cat a fost descarcat din torent 
      - Nume parametru: haveValid 
      - Clasa: Connection
 - Modificat verificarile realizate la adaugarea unui torent ( spatiu raportat de transmission - spatiu necesar pentru torentele ce se descarca) 
      - Clasa : RunThread 

Fisierele pentru download : 
[Modifiedfiles.zip](https://github.com/KiralyCraft/FilelistCrawlerServerVersion/files/2690147/Modifiedfiles.zip)

Sau pastebin : 
 - Connection : https://pastebin.com/rJymuh8t
 - RunThread : https://pastebin.com/THY95Bc6

L.E. clasa Runthread linia 605 trebuie sters **long** altfel da eroare de duplicate variables, _SORRY_

**Comment by KiralyCraft** [comment]
Mult apreciat. Am testat implementarea si pana acum merge perfect. Daca reapar probleme pe tema am sa redeschid issue-ul. So far so good! :D
