### ISSUE TITLE
Unable to get 1st torrente page 

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#4]
[13:58] Clearing Torrent Cache ...
[13:58] Getting the 1st torrent page ...
[13:58] Response Code : 302
[13:58]
[13:58] =====WARNING=====
[13:58] Response code was supposed to be 200, it was 302
[13:58] Check your Filelist.ro login data, it might not be correct
[13:58] =================

**Comment by KiralyCraft** [comment]
Hmm oare asta era la treaba cu login din 3 locatii diferite?

**Comment by MosfetWall** [comment]
Nu cred, in acceasi zi, pentru test, am facut o app (java, care face Login & Retur pentru pagina de browse).
Mini applicatia nu a avut probleme. 
O sa incerc sa recomplezi codul sursa sa vad daca mai are probleme.

**Comment by KiralyCraft** [comment]
Am adaugat acum o optiune de "Login on any ip", daca host-ul de Transmission nu e "127.0.0.1" sau "localhost" atunci se activeaza ca sa previna invalidarea datelor de autentificare. Probabil ar trebui sa rezolve problema asta. Nu sunt sigur totusi daca ar trebui activata respectiva optiune si pentru localhost

**Comment by MosfetWall** [comment]
Merge.
Eu folosesc aplicatia pe un Ubuntu 18.04 LTS Server, initial ma gandeam ca problema sa nu fi aiba legatura cu absenta GUI-ului.  De aici si miniaplicatia mentionata.

**Comment by KiralyCraft** [comment]
Am adaugat aseara modificarile pentru verificarile de spatiu, inca nu am facut un release pentru ca astept sa  se umple 1TB de torrente sa vedem daca mai face urat, recomand sa compilezi ultima versiune pentru test; Pana acum se comporta corect
