### ISSUE TITLE
Propunere modificare selectie torente pt cleanup

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#7]
1) Inadvertenta coment si cod
`if ((ti.getUploadRatio()>1.0f || ti.getTimeAddedSeconds()>172800)) //daca are 48 de ore si nu o mai facut upload de o zi`
codul verifica daca are ratia mai mare de 1 **SAU** timpul de seed de cel putin 48h - ceea ce este corect.

2) Ar trebui verificat si daca a mai facut in ultima ora, evitand astfel situatia cand se sterge un torrent care indeplineste conditiile dar care face upload in prezent. 
`if ((ti.getUploadRatio()>1.0f || ti.getTimeAddedSeconds()>172800) && (ti.getLastActivitySeconds()>3600)) //daca are 48 de ore la seed sau ratie >1 si nu a mai facut trafic (upload) de o ora`

ar mai fi o chestie sa verificam daca viteza medie de transfer in ultima ora depaseste X valoare, astfel se poate sterge un torrent care face uploade vu o viteza foarte mica.

_Just my 2 cents_ 
 

L.E. 

_Devin carcotas -- si vin cu o observatie fara a oferi solutia concreta._
 Cand este evaluat un torent pentru stergere in ideea de a evita hit and run se verifica ratia si timpul trecut de la adaugarea lui (`getTimeAddedSeconds`). 
Din ce stiu FL ia in considerare doar timpul de seed (dupa ce ai 100% din torrent). 
Ca atare propun sa extragem si campul `secondsSeeding` pentru torentele din transmission, urmand ca valoare acestuia sa fie utilizata in cadrul evaluari pentru stergere. 
Modificarea nu este una majora dar, din pacate, nu am timp sa o implementez acum. 
Sper sa vin cu o propunere concreta maine. 

P.S. Pana in prezent nu am asteptat 48h dupa nici un torent, toate au fost sterse (automat sau manual) fiind validata conditia de ratie >1.

**Comment by KiralyCraft** [comment]
Am refactorizat acum comentariile, dar referitor la situatia cu timpul de seed e mai problematic, dupa parerea mea. Ar trebui sa facem o statistica in situatia asta. Daca un torrent care sta la seed, indiferent de viteza de upload la momentul cleanup-ului, trebuie sters pentru a face spatiu, cum ar trebui procedat astfel incat media vitezei de upload intr-un interval de timp sa fie cat mai mare?
Sa consideram urmatorul exemplu:

- Torrentul X sta la seed. Are ratio 1 si uploadeaza cu 1 MB/s.
- Torrentul Y trebuie descarcat deoarece indeplineste conditiile, dar nu mai este spatiu. 
- Avem doua posibilitati:
 

1. Stergem torrentul X, si pornim descarcarea lui Y. Astfel, toti cei care descarca Y in acel moment vor deveni peers pentru upload, ca urmare sunt mai multe sanse ca viteza de upload pentru Y sa o depaseasca pe cea a lui X, pe termen lung (aka durata descarcarii torrentului Y). Fiind torrent mai nou, va aparea pe prima pagina mai mult decat X, avand mai multe sanse de download si implicit peers.
2. Nu stergem torrentul X deoarece inca face upload. Posibil sa nu mai fie pe prima pagina, asa ca sansele de download sunt mai mici decat a le lui Y. Astfel, ratam toti peers pentru torrentul Y (care nu il putem descarca, probabil), dar facem upload cu 1 MB/s constant.

De asemenea, cele doua posibilitati au consecinte in comunitate:
- Daca stergem egoist torrentul cand avem nevoie de spatiu, nu vom mai fi seederi, iar torrentul are sanse sa moara (infime, dar totusi sunt)
- Daca nu stergem torrentul doar cand nu mai prezinta interes (optiunea 2), vom fi seederi pentru o perioada mai lunga de timp, ajutand astfel comunitatea. Evident primim si FLCoins (daca suntem sub 1 TB)

In concluzie, consider ca ar fi corect sa introducem o optiune cu ajutorul careia sa putem activa sau dezactiva stergerea unui torrent care inca face upload. Eventual doua optiuni, un "minimum treshold": i.e. nu stergem torrentul terminat doar daca viteza de upload e sub A mb/s. Am sa intreb totusi cand se ia in considerare timpul de seed, sa fie sigur.
