### ISSUE TITLE
IndexOutOfBoundsException & NullPointerException la stergerea unui torrent.

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#8]
A facut buba ... :) 

> [17:21] Clearing Torrent Cache ...
> [17:21] Getting the 1st torrent page ...
> [17:21] Response Code : 200
> [17:21] Grabbing torrent data ...
> [17:21] Analyzing results ...
> [17:21] Asking Transmission how much free space there is.
> [17:21] Got response: 255385600 bytes = 255 MB
> [17:21] Asking Transmission how much free is required for current downloading torrents.
> [17:21] Got response: 0 bytes = 0 MB
> [17:21] ==========================================
> [17:21] Gloria.1980.720p.BluRay.AAC.2.0.x264-SPEED - Checking requirements ...
> [17:21] Not enough space to download Gloria.1980.720p.BluRay.AAC.2.0.x264-SPEED. It requires 10.99 GB
> [17:21] Will ask Transmission to do a cleanup.
> Removing torrent instance from Transmission
> Removing associated files for:Hunter.Street.S01.1080p.NICK.WEBRip.AAC2.0.x264-TVSmash
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>         at java.util.ArrayList.rangeCheck(ArrayList.java:657)
>         at java.util.ArrayList.get(ArrayList.java:433)
>         at com.google.gson.JsonArray.get(JsonArray.java:92)
>         at com.kiralycraft.tapidiy.Connection.getTorrentFiles(Connection.java:691)
>         at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:279)
>         at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:604)
>         at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
> [17:21] ERROR OCCURED! null
> java.lang.NullPointerException
>         at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:280)
>         at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:604)
>         at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
> 

Retest, pentru siguranta 

> [17:33] Clearing Torrent Cache ...
> [17:33] Getting the 1st torrent page ...
> [17:33] Response Code : 200
> [17:33] Grabbing torrent data ...
> [17:33] Analyzing results ...
> [17:33] Asking Transmission how much free space there is.
> [17:33] Got response: 28562792448 bytes = 28562 MB
> [17:33] Asking Transmission how much free is required for current downloading torrents.
> [17:33] Got response: 0 bytes = 0 MB
> [17:33] ==========================================
> [17:33] Gotham.S04.720p.BluRay.DD5.1.x264-SbR - Checking requirements ...
> [17:33] Not enough space to download Gotham.S04.720p.BluRay.DD5.1.x264-SbR. It requires 46.21 GB
> [17:33] Will ask Transmission to do a cleanup.
> Removing torrent instance from Transmission
> Removing associated files for:Avast!.Internet.SecurityPremier.Antivirus.v19.1.2360.Build.19.1.4142.Avast!.Internet.SecurityPremier.Antivirus.v19.1.2360.Build.19.1.4142
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>         at java.util.ArrayList.rangeCheck(ArrayList.java:657)
>         at java.util.ArrayList.get(ArrayList.java:433)
>         at com.google.gson.JsonArray.get(JsonArray.java:92)
>         at com.kiralycraft.tapidiy.Connection.getTorrentFiles(Connection.java:691)
>         at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:279)
>         at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:604)
>         at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
> [17:33] ERROR OCCURED! null
> java.lang.NullPointerException
>         at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:280)
>         at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:604)
>         at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
>

**Comment by KiralyCraft** [comment]
Ah, perfect. Chiar azi a postat cineva eroarea asta iar cand sa dau pe ea a sters-o, ma uit acum ce e problema.

**Comment by KiralyCraft** [comment]
Evident ca face buba, nu stiu de ce mi s-a parut perfect logic sa sterg mai intai torrentul din Transmission apoi sa-l intreb despre el 🔧

**Comment by KiralyCraft** [comment]
Am reparat, poti confirma ca e rezolvat?

**Comment by MosfetWall** [comment]
Cred ca da.
Momentan îmi tot da o eroare ca nu poate sterge, cel mai probabil este ceva de la permisiuni.
Ciudat însă este ca are același comportament și când îl execut de pe root.

Momentan nu mai pot sa testez. (mi-am uitat laptopul la birou și nu ma încântă ideea de remote de pe telefon).

**Comment by KiralyCraft** [comment]
Am adaugat niste debug messages, poate o sa ajute. Daca bine tin minte, nici la mine nu mergea delete. Din pacate aplicatia o testez in modul remote acum, ca sa vad daca merge corect stergerea remote, asa ca nu am cum sa testez local. Posibil sa fie path-ul gresit catre fisier, dar daca e cazul va aparea in debug messages.

**Comment by MosfetWall** [comment]
Încerc mâine dimineață, când ajung la birou.

**Comment by MosfetWall** [comment]
Nu vad mesajele pt debug. :( 

> [16:09] Got response: 6765395968 bytes = 6765 MB
> [16:09] Asking Transmission how much free is required for current downloading torrents.
> [16:09] Got response: 5564792832 bytes = 5564 MB
> [16:09] ==========================================
> [16:09] Austin.Powers.in.Goldmember.2002.1080p.BluRay.DTS.x264-Skazhutin - Checking requirements ...
> [16:09] Not enough space to download Austin.Powers.in.Goldmember.2002.1080p.BluRay.DTS.x264-Skazhutin. It requires 10.97 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [16:09] ==========================================
> [16:09]
> [16:09] ==========================================
> [16:09] Happy.Death.Day.2017.1080p.BluRay.DTS.x264-KASHMiR - Checking requirements ...
> [16:09] Not enough space to download Happy.Death.Day.2017.1080p.BluRay.DTS.x264-KASHMiR. It requires 11.09 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [16:09] ==========================================
> [16:09]
> [16:09] ==========================================
> [16:09] Saving.Private.Ryan.1998.1080p.BluRay.DTS.x264-EbP - Checking requirements ...
> [16:09] Not enough space to download Saving.Private.Ryan.1998.1080p.BluRay.DTS.x264-EbP. It requires 24.45 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [16:09] ==========================================
> [16:09]
> [16:09] ==========================================
> [16:09] Sense.and.Sensibility.1995.720p.BluRay.DD5.1.x264-Ingui - Checking requirements ...
> [16:09] Not enough space to download Sense.and.Sensibility.1995.720p.BluRay.DD5.1.x264-Ingui. It requires 9.16 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [16:09] ==========================================
> [16:09]
> [16:09] ==========================================
> [16:09] Poseidon.2006.1080p.BluRay.DTS.x264-SbR - Checking requirements ...
> [16:09] Not enough space to download Poseidon.2006.1080p.BluRay.DTS.x264-SbR. It requires 10.96 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [16:09] ==========================================
> [16:09]
> [16:09] ==========================================
> [16:09] The.Man.in.the.Iron.Mask.1998.1080p.BluRay.DTS.x264-CtrlHD - Checking requirements ...
> [16:09] Not enough space to download The.Man.in.the.Iron.Mask.1998.1080p.BluRay.DTS.x264-CtrlHD. It requires 13.94 GB
> [16:09] Will ask Transmission to do a cleanup.
> [16:09] Transmission failed to clean up enough space for this torrent, so we're skipping it.
>

**Comment by KiralyCraft** [comment]
Mesajul de debug apare doar cand se sterge un torrent, respectiv fisierele sale. Sunt 80% sigur ca acum merge, fiindca inainte avea buba deoarece disparea torrentul (si detaliile despre fisierele sale) inainte sa intrebe de fisiere. Acum am interschimbat cele doua requesturi, mai intai intreaba care sunt fisierele apoi il stere din Transmission apoi sterge fisierele in sine de pe disk.
