### ISSUE TITLE
Permisiuni pentru fisierele descarcate

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#9]
Fisierele descarcate de transmission au urmatoarele permisiuni
```
drwxr-sr-x  2 debian-transmission mosfet 4096 Jan  9 07:58 37.Days.S01.720p.BluRay.x264-SPLiTSViLLE
drwxr-sr-x  2 debian-transmission mosfet 4096 Jan  9 07:57 MAD.S02.720p.WEB-DL.AAC2.0.H264-NTb
drwxr-sr-x 25 debian-transmission mosfet 4096 Jan  8 23:27 Murder.She.Wrote.S01.1080p.AMZN.WEB-DL.DD2.0.H.264-MZABI
drwxr-sr-x  2 debian-transmission mosfet 4096 Jan  9 06:48 Riphagen.2017.720p.BluRay.DD2.0.x264-SbR
```
cu alte cuvinte : 

-  owner este : debian-transmission
-  permisiunile pe fisiere sunt  drwxr-sr-x  , adica owner : RWX, grup R-X, other R-X 
-  scriptul este executat de userul normal sau root

Cred ca este evidenta problema si din pacate tine mai mult de transmission decat de aplicatia pentru seed.
Stergerea remote sau prin transmission merge fara probleme fiind realizata de userul debian-transmission.
Revin cu o solutie, in speranta ca voi gasi una.

**Comment by KiralyCraft** [comment]
Am avut si eu problema asta, solutia a fost sa modific mask-ul din settings.json. Daca il pui pe "umask": 0, toate fisierele/folderele vor fi create cu permisiuni 777. Poate nu e tocmai safe, dar macar merge. O alta solutie executarea crawlerului ca debian-transmission. A doua varianta nu am incercat-o, dar posibil sa mearga.

**Comment by MosfetWall** [comment]
Era pregatit in draft dar asteptam sa confirm functionarea coreta inainte sa dau submit. 

Modificarea maskului pentru fisierele create de transmission 

> in fisierul de setari pentru transmission din **"umask": 18,** in **"umask": 0,**

Adaugarea userului de logon in grupul utilizat de transmission

> Configure Users and Permissions
> It is recommended that Transmission runs under it’s own username for security reasons. This creates a few issues with file and folder access by Transmission as well as your account (let us assume it is user).
> 
> Add the username user to the group debian-transmission:
> 
> 
> sudo usermod -a -G debian-transmission user
> NOTE: Change "user" to you own user login name. 
> 
> NOTE: When adding a user to a new group, the user must log out and log back in for it to take affect. A reboot will also accomplish this.

**Comment by MosfetWall** [comment]
Still no success 

> [15:21] ==========================================
> [15:21] Brestskaya.krepost.2010.720p.BluRay.DD5.1.x264-VietHD - Checking requirements ...
> [15:21] Not enough space to download Brestskaya.krepost.2010.720p.BluRay.DD5.1.x264-VietHD. It requires 10.26 GB
> [15:21] Will ask Transmission to do a cleanup.
> Getting associated files for:Seriously.Funny.Kids.S01.720p.WEB-DL.AAC2.0.h.264-ETP
> Removing torrent instance from Transmission
> Removing associated files for:Seriously.Funny.Kids.S01.720p.WEB-DL.AAC2.0.h.264-ETP
> Expecting file at: "/media/storage/data/Seriously.Funny.Kids.S01.720p.WEB-DL.AAC2.0.h.264-ETP/Seriously.Funny.Kids.S01E01.Does.He.Do.Tricks.720p.WEB-DL.AAC2.0.h.264-ETP.mkv". Does it exist? true.
> Erasing Seriously.Funny.Kids.S01.720p.WEB-DL.AAC2.0.h.264-ETP/Seriously.Funny.Kids.S01E01.Does.He.Do.Tricks.720p.WEB-DL.AAC2.0.h.264-ETP.mkv
> Failed to delete! Will retry in 1 second. Retry #1
> Failed to delete! Will retry in 1 second. Retry #2
> Failed to delete! Will retry in 1 second. Retry #3
> Failed to delete! Will retry in 1 second. Retry #4
> Failed to delete! Will retry in 1 second. Retry #5
> Failed to delete! Will retry in 1 second. Retry #6
> Failed to delete! Will retry in 1 second. Retry #7
> Failed to delete! Will retry in 1 second. Retry #8
> Failed to delete! Will retry in 1 second. Retry #9
> Failed to delete after 10 tries! Aborting ...
> [15:21] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [15:21] ==========================================
> [15:21]
> [15:21] ==========================================
> [15:21] Submarine.2011.720p.BluRay.DD5.1.x264-DON - Checking requirements ...
> [15:21] Not enough space to download Submarine.2011.720p.BluRay.DD5.1.x264-DON. It requires 5.54 GB
> [15:21] Will ask Transmission to do a cleanup.
> Getting associated files for:Master.of.Arms.S01.1080p.WEB-DL.AAC2.0.x264-RTN
> Removing torrent instance from Transmission
> Removing associated files for:Master.of.Arms.S01.1080p.WEB-DL.AAC2.0.x264-RTN
> Expecting file at: "/media/storage/data/Master.of.Arms.S01.1080p.WEB-DL.AAC2.0.x264-RTN/Master.of.Arms.S01E01.Flintlock.Axe.Pistol.1080p.WEB-DL.AAC2.0.x264-RTN.mkv". Does it exist? true.
> Erasing Master.of.Arms.S01.1080p.WEB-DL.AAC2.0.x264-RTN/Master.of.Arms.S01E01.Flintlock.Axe.Pistol.1080p.WEB-DL.AAC2.0.x264-RTN.mkv
> Failed to delete! Will retry in 1 second. Retry #1
> Failed to delete! Will retry in 1 second. Retry #2
> Failed to delete! Will retry in 1 second. Retry #3
> Failed to delete! Will retry in 1 second. Retry #4
> Failed to delete! Will retry in 1 second. Retry #5
> Failed to delete! Will retry in 1 second. Retry #6
> Failed to delete! Will retry in 1 second. Retry #7
> Failed to delete! Will retry in 1 second. Retry #8
> Failed to delete! Will retry in 1 second. Retry #9
> Failed to delete after 10 tries! Aborting ...
> [15:22] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [15:22] ==========================================
> [15:22]
> [15:22] ==========================================
> [15:22] An.Unfinished.Life.2005.720p.BluRay.DD5.1.x264-iNFLiKTED - Checking requirements ...
> [15:22] Not enough space to download An.Unfinished.Life.2005.720p.BluRay.DD5.1.x264-iNFLiKTED. It requires 4.9 GB
> [15:22] Will ask Transmission to do a cleanup.
> [15:22] Transmission failed to clean up enough space for this torrent, so we're skipping it.
> [15:22] ==========================================
> [15:22]
>

**Comment by KiralyCraft** [comment]
Fixed, stergerea se face prin Transmission acum, fara interventie manuala la filesystem
